/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/auth/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["fetchAuthSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getClients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listClients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getEmployees"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listEmployees"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthcheck/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pingHealthcheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getReservations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listReservations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room-types/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRoomType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room-types/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteRoomType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room-types/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getRoomTypes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room-types/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listRoomTypes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room-types/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreRoomType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room-types/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateRoomType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getRooms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listRooms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        BaseResponse: {
            status: components["schemas"]["Status"];
        };
        Client: {
            active: boolean;
            /** Format: date-time */
            creationDate: string;
            id: number;
            identityNumber: string;
            name: string;
            phone: string;
        };
        ClientCreateInput: {
            identityNumber: string;
            name: string;
            phone: string;
        };
        ClientDataResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Client"];
        };
        ClientGetInput: {
            clientIds: number[];
            fields?: ("id" | "name" | "identityNumber" | "phone" | "active" | "creationDate")[];
        };
        ClientGetResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Client"][];
        };
        ClientListInput: {
            count: number;
            fields?: ("id" | "name" | "identityNumber" | "phone" | "active" | "creationDate")[];
            includeDeleted?: boolean;
            page: number;
            search?: {
                query: string;
                searchIn: ("name" | "identityNumber" | "phone")[];
            };
            sort?: {
                /** @enum {string} */
                by?: "name" | "creationDate";
                /** @enum {string} */
                order?: "asc" | "desc";
            };
        };
        ClientListResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Client"][];
            page?: number;
            total?: number;
        };
        ClientUpdateInput: {
            active?: boolean;
            clientId: number;
            identityNumber?: string;
            name?: string;
            phone?: string;
        };
        Employee: {
            active: boolean;
            /** Format: date-time */
            creationDate: string;
            /** Format: email */
            email: string;
            id: number;
            identityNumber: string;
            name: string;
            phone: string;
            /** @enum {string} */
            role: "Manager" | "Receptionist" | "Housekeeper" | "Maintenance";
            salary: number;
        };
        EmployeeCreateInput: {
            accessKey: string;
            /** Format: email */
            email: string;
            identityNumber: string;
            name: string;
            phone: string;
            /** @enum {string} */
            role: "Manager" | "Receptionist" | "Housekeeper" | "Maintenance";
            salary: number;
        };
        EmployeeDataResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Employee"];
        };
        EmployeeGetInput: {
            employeeIds: number[];
            fields?: ("id" | "identityNumber" | "phone" | "salary" | "name" | "email" | "role" | "active" | "creationDate")[];
        };
        EmployeeGetResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Employee"][];
        };
        EmployeeListInput: {
            count: number;
            fields?: ("id" | "identityNumber" | "phone" | "salary" | "name" | "email" | "role" | "active" | "creationDate")[];
            filters?: {
                active?: boolean;
                /** @enum {string} */
                role?: "Manager" | "Receptionist" | "Housekeeper" | "Maintenance";
            };
            includeDeleted?: boolean;
            page: number;
            search?: {
                query: string;
                searchIn: ("identityNumber" | "phone" | "name" | "email" | "role")[];
            };
            sort?: {
                /** @enum {string} */
                by?: "name" | "role" | "creationDate";
                /** @enum {string} */
                order?: "asc" | "desc";
            };
        };
        EmployeeListResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Employee"][];
            page?: number;
            total?: number;
        };
        EmployeeUpdateInput: {
            accessKey?: string;
            active?: boolean;
            /** Format: email */
            email?: string;
            employeeId: number;
            identityNumber?: string;
            name?: string;
            phone?: string;
            /** @enum {string} */
            role?: "Manager" | "Receptionist" | "Housekeeper" | "Maintenance";
            salary?: number;
        };
        FetchAuthResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["SessionEmployee"];
        };
        HealthcheckResponse: components["schemas"]["BaseResponse"] & {
            /** @example pong */
            message?: string;
        };
        LoginInput: {
            accessKey: string;
            /** Format: email */
            email: string;
        };
        LoginResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["SessionEmployee"];
        };
        LogoutResponse: components["schemas"]["BaseResponse"] & {
            result?: boolean;
        };
        Reservation: {
            active: boolean;
            charge: number;
            /** Format: date-time */
            checkInDate: string;
            /** Format: date-time */
            checkOutDate: string;
            clientId: number;
            /** Format: date-time */
            creationDate: string;
            id: number;
            roomId: number;
            /** @enum {string} */
            status: "Pending" | "Confirmed" | "CheckedIn" | "CheckedOut" | "Cancelled";
        };
        ReservationCreateInput: {
            charge: number;
            /** Format: date-time */
            checkInDate: string;
            /** Format: date-time */
            checkOutDate: string;
            clientId: number;
            roomId: number;
            /** @enum {string} */
            status?: "Pending" | "Confirmed" | "CheckedIn" | "CheckedOut" | "Cancelled";
        };
        ReservationDataResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Reservation"];
        };
        ReservationGetInput: {
            fields?: ("id" | "clientId" | "roomId" | "status" | "checkInDate" | "checkOutDate" | "charge" | "active" | "creationDate")[];
            reservationIds: number[];
        };
        ReservationGetResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Reservation"][];
        };
        ReservationListInput: {
            count: number;
            fields?: ("id" | "clientId" | "roomId" | "status" | "checkInDate" | "checkOutDate" | "charge" | "active" | "creationDate")[];
            filters?: {
                active?: boolean;
                clientId?: number;
                roomId?: number;
                /** @enum {string} */
                status?: "Pending" | "Confirmed" | "CheckedIn" | "CheckedOut" | "Cancelled";
            };
            includeDeleted?: boolean;
            page: number;
            search?: {
                query: string;
                searchIn: "status"[];
            };
            sort?: {
                /** @enum {string} */
                by?: "checkInDate" | "checkOutDate" | "creationDate" | "status";
                /** @enum {string} */
                order?: "asc" | "desc";
            };
        };
        ReservationListResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Reservation"][];
            page?: number;
            total?: number;
        };
        ReservationUpdateInput: {
            active?: boolean;
            charge?: number;
            /** Format: date-time */
            checkInDate?: string;
            /** Format: date-time */
            checkOutDate?: string;
            clientId?: number;
            reservationId: number;
            roomId?: number;
            /** @enum {string} */
            status?: "Pending" | "Confirmed" | "CheckedIn" | "CheckedOut" | "Cancelled";
        };
        ResultResponse: components["schemas"]["BaseResponse"] & {
            result?: boolean;
        };
        Room: {
            active: boolean;
            /** Format: date-time */
            creationDate: string;
            description: string;
            id: number;
            number: string;
            roomTypeId: number;
            /** @enum {string} */
            state: "Avaliable" | "Occupied" | "Maintenance";
        };
        RoomCreateInput: {
            description: string;
            number: string;
            roomTypeId: number;
            /** @enum {string} */
            state: "Avaliable" | "Occupied" | "Maintenance";
        };
        RoomDataResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Room"];
        };
        RoomGetInput: {
            fields?: ("id" | "number" | "roomTypeId" | "description" | "state" | "active" | "creationDate")[];
            roomIds: number[];
        };
        RoomGetResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Room"][];
        };
        RoomListInput: {
            count: number;
            fields?: ("id" | "number" | "roomTypeId" | "description" | "state" | "active" | "creationDate")[];
            filters?: {
                active?: boolean;
                roomTypeId?: number;
                /** @enum {string} */
                state?: "Avaliable" | "Occupied" | "Maintenance";
            };
            includeDeleted?: boolean;
            page: number;
            search?: {
                query: string;
                searchIn: ("number" | "description" | "state")[];
            };
            sort?: {
                /** @enum {string} */
                by?: "number" | "state" | "creationDate";
                /** @enum {string} */
                order?: "asc" | "desc";
            };
        };
        RoomListResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["Room"][];
            page?: number;
            total?: number;
        };
        RoomType: {
            active: boolean;
            /** Format: date-time */
            creationDate: string;
            description: string;
            id: number;
            maxOccupancy: number;
            price: number;
        };
        RoomTypeCreateInput: {
            description: string;
            maxOccupancy: number;
            price: number;
        };
        RoomTypeDataResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["RoomType"];
        };
        RoomTypeGetInput: {
            fields?: ("id" | "description" | "maxOccupancy" | "price" | "active" | "creationDate")[];
            roomTypeIds: number[];
        };
        RoomTypeGetResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["RoomType"][];
        };
        RoomTypeListInput: {
            count: number;
            fields?: ("id" | "description" | "maxOccupancy" | "price" | "active" | "creationDate")[];
            includeDeleted?: boolean;
            page: number;
            search?: {
                query: string;
                searchIn: "description"[];
            };
            sort?: {
                /** @enum {string} */
                by?: "description" | "maxOccupancy" | "price" | "creationDate";
                /** @enum {string} */
                order?: "asc" | "desc";
            };
        };
        RoomTypeListResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["RoomType"][];
            page?: number;
            total?: number;
        };
        RoomTypeUpdateInput: {
            active?: boolean;
            description?: string;
            maxOccupancy?: number;
            price?: number;
            roomTypeId: number;
        };
        RoomUpdateInput: {
            active?: boolean;
            description?: string;
            number?: string;
            roomId: number;
            roomTypeId?: number;
            /** @enum {string} */
            state?: "Avaliable" | "Occupied" | "Maintenance";
        };
        SessionEmployee: {
            active: boolean;
            /** Format: date-time */
            creationDate: string;
            /** Format: email */
            email: string;
            id: number;
            identityNumber: string;
            name: string;
            phone: string;
            /** @enum {string} */
            role: "Manager" | "Receptionist" | "Housekeeper" | "Maintenance";
            salary: number;
        };
        /** @enum {string} */
        Status: "success" | "forbidden" | "duplicate-record" | "not-found" | "invalid-request" | "internal-error";
    };
    responses: never;
    parameters: never;
    requestBodies: {
        ClientCreateRequest: {
            content: {
                "application/json": components["schemas"]["ClientCreateInput"];
            };
        };
        ClientDeleteRequest: {
            content: {
                "application/json": {
                    clientId: number;
                };
            };
        };
        ClientGetRequest: {
            content: {
                "application/json": components["schemas"]["ClientGetInput"];
            };
        };
        ClientListRequest: {
            content: {
                "application/json": components["schemas"]["ClientListInput"];
            };
        };
        ClientRestoreRequest: {
            content: {
                "application/json": {
                    clientId: number;
                };
            };
        };
        ClientUpdateRequest: {
            content: {
                "application/json": components["schemas"]["ClientUpdateInput"];
            };
        };
        EmployeeCreateRequest: {
            content: {
                "application/json": components["schemas"]["EmployeeCreateInput"];
            };
        };
        EmployeeDeleteRequest: {
            content: {
                "application/json": {
                    employeeId: number;
                };
            };
        };
        EmployeeGetRequest: {
            content: {
                "application/json": components["schemas"]["EmployeeGetInput"];
            };
        };
        EmployeeListRequest: {
            content: {
                "application/json": components["schemas"]["EmployeeListInput"];
            };
        };
        EmployeeRestoreRequest: {
            content: {
                "application/json": {
                    employeeId: number;
                };
            };
        };
        EmployeeUpdateRequest: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdateInput"];
            };
        };
        LoginRequest: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        ReservationCreateRequest: {
            content: {
                "application/json": components["schemas"]["ReservationCreateInput"];
            };
        };
        ReservationDeleteRequest: {
            content: {
                "application/json": {
                    reservationId: number;
                };
            };
        };
        ReservationGetRequest: {
            content: {
                "application/json": components["schemas"]["ReservationGetInput"];
            };
        };
        ReservationListRequest: {
            content: {
                "application/json": components["schemas"]["ReservationListInput"];
            };
        };
        ReservationRestoreRequest: {
            content: {
                "application/json": {
                    reservationId: number;
                };
            };
        };
        ReservationUpdateRequest: {
            content: {
                "application/json": components["schemas"]["ReservationUpdateInput"];
            };
        };
        RoomCreateRequest: {
            content: {
                "application/json": components["schemas"]["RoomCreateInput"];
            };
        };
        RoomDeleteRequest: {
            content: {
                "application/json": {
                    roomId: number;
                };
            };
        };
        RoomGetRequest: {
            content: {
                "application/json": components["schemas"]["RoomGetInput"];
            };
        };
        RoomListRequest: {
            content: {
                "application/json": components["schemas"]["RoomListInput"];
            };
        };
        RoomRestoreRequest: {
            content: {
                "application/json": {
                    roomId: number;
                };
            };
        };
        RoomTypeCreateRequest: {
            content: {
                "application/json": components["schemas"]["RoomTypeCreateInput"];
            };
        };
        RoomTypeDeleteRequest: {
            content: {
                "application/json": {
                    roomTypeId: number;
                };
            };
        };
        RoomTypeGetRequest: {
            content: {
                "application/json": components["schemas"]["RoomTypeGetInput"];
            };
        };
        RoomTypeListRequest: {
            content: {
                "application/json": components["schemas"]["RoomTypeListInput"];
            };
        };
        RoomTypeRestoreRequest: {
            content: {
                "application/json": {
                    roomTypeId: number;
                };
            };
        };
        RoomTypeUpdateRequest: {
            content: {
                "application/json": components["schemas"]["RoomTypeUpdateInput"];
            };
        };
        RoomUpdateRequest: {
            content: {
                "application/json": components["schemas"]["RoomUpdateInput"];
            };
        };
    };
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    fetchAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fetch current authenticated employee session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchAuthResponse"];
                };
            };
        };
    };
    loginAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LoginRequest"];
        responses: {
            /** @description Login response */
            200: {
                headers: {
                    /** @description HttpOnly JWT cookie containing the session token. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logoutAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout response and clear auth cookie */
            200: {
                headers: {
                    /** @description Clears the session cookie on logout. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    createClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ClientCreateRequest"];
        responses: {
            /** @description Create client response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDataResponse"];
                };
            };
        };
    };
    deleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ClientDeleteRequest"];
        responses: {
            /** @description Delete client response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    getClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ClientGetRequest"];
        responses: {
            /** @description Get clients response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientGetResponse"];
                };
            };
        };
    };
    listClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ClientListRequest"];
        responses: {
            /** @description List clients response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientListResponse"];
                };
            };
        };
    };
    restoreClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ClientRestoreRequest"];
        responses: {
            /** @description Restore client response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    updateClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ClientUpdateRequest"];
        responses: {
            /** @description Update client response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDataResponse"];
                };
            };
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmployeeCreateRequest"];
        responses: {
            /** @description Create employee response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDataResponse"];
                };
            };
        };
    };
    deleteEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmployeeDeleteRequest"];
        responses: {
            /** @description Delete employee response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    getEmployees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmployeeGetRequest"];
        responses: {
            /** @description Get employees response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeGetResponse"];
                };
            };
        };
    };
    listEmployees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmployeeListRequest"];
        responses: {
            /** @description List employees response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeListResponse"];
                };
            };
        };
    };
    restoreEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmployeeRestoreRequest"];
        responses: {
            /** @description Restore employee response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    updateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmployeeUpdateRequest"];
        responses: {
            /** @description Update employee response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDataResponse"];
                };
            };
        };
    };
    pingHealthcheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthcheck response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthcheckResponse"];
                };
            };
        };
    };
    createReservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ReservationCreateRequest"];
        responses: {
            /** @description Create reservation response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationDataResponse"];
                };
            };
        };
    };
    deleteReservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ReservationDeleteRequest"];
        responses: {
            /** @description Delete reservation response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    getReservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ReservationGetRequest"];
        responses: {
            /** @description Get reservations response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationGetResponse"];
                };
            };
        };
    };
    listReservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ReservationListRequest"];
        responses: {
            /** @description List reservations response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationListResponse"];
                };
            };
        };
    };
    restoreReservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ReservationRestoreRequest"];
        responses: {
            /** @description Restore reservation response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    updateReservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ReservationUpdateRequest"];
        responses: {
            /** @description Update reservation response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationDataResponse"];
                };
            };
        };
    };
    createRoomType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomTypeCreateRequest"];
        responses: {
            /** @description Create room type response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomTypeDataResponse"];
                };
            };
        };
    };
    deleteRoomType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomTypeDeleteRequest"];
        responses: {
            /** @description Delete room type response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    getRoomTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomTypeGetRequest"];
        responses: {
            /** @description Get room types response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomTypeGetResponse"];
                };
            };
        };
    };
    listRoomTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomTypeListRequest"];
        responses: {
            /** @description List room types response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomTypeListResponse"];
                };
            };
        };
    };
    restoreRoomType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomTypeRestoreRequest"];
        responses: {
            /** @description Restore room type response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    updateRoomType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomTypeUpdateRequest"];
        responses: {
            /** @description Update room type response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomTypeDataResponse"];
                };
            };
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomCreateRequest"];
        responses: {
            /** @description Create room response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomDataResponse"];
                };
            };
        };
    };
    deleteRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomDeleteRequest"];
        responses: {
            /** @description Delete room response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    getRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomGetRequest"];
        responses: {
            /** @description Get rooms response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomGetResponse"];
                };
            };
        };
    };
    listRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomListRequest"];
        responses: {
            /** @description List rooms response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomListResponse"];
                };
            };
        };
    };
    restoreRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomRestoreRequest"];
        responses: {
            /** @description Restore room response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
        };
    };
    updateRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoomUpdateRequest"];
        responses: {
            /** @description Update room response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomDataResponse"];
                };
            };
        };
    };
}
