/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/clients/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listClients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updateClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Client: {
            _id?: string;
            name?: string;
            identityNumber?: string;
            phone?: string;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SuccessResponse: {
            success?: boolean;
        };
        ListClientResponse: {
            data?: components["schemas"]["Client"][];
            total?: number;
            page?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        CreateClientRequest: {
            content: {
                "application/json": {
                    name: string;
                    identityNumber: string;
                    phone?: string;
                };
            };
        };
        GetClientRequest: {
            content: {
                "application/json": {
                    clientIds: string[];
                    fields?: ("_id" | "name" | "identityNumber" | "phone" | "isActive" | "createdAt")[];
                };
            };
        };
        ListClientRequest: {
            content: {
                "application/json": {
                    count: number;
                    page: number;
                    fields?: ("_id" | "name" | "identityNumber" | "phone" | "isActive" | "createdAt")[];
                    includeDeleted?: boolean;
                    search?: {
                        query?: string;
                        searchIn?: ("name" | "identityNumber" | "phone")[];
                    };
                    sort?: {
                        /** @enum {string} */
                        by?: "name" | "createdAt" | "updatedAt";
                        /** @enum {string} */
                        order?: "asc" | "desc";
                    };
                };
            };
        };
        UpdateClientRequest: {
            content: {
                "application/json": {
                    clientId: string;
                    name?: string;
                    identityNumber?: string;
                    phone?: string;
                    isActive?: boolean;
                };
            };
        };
        DeleteClientRequest: {
            content: {
                "application/json": {
                    clientId: string;
                };
            };
        };
        RestoreClientRequest: {
            content: {
                "application/json": {
                    clientId: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateClientRequest"];
        responses: {
            /** @description Created client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
        };
    };
    getClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GetClientRequest"];
        responses: {
            /** @description List of matching clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"][];
                };
            };
        };
    };
    listClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ListClientRequest"];
        responses: {
            /** @description Paginated client list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListClientResponse"];
                };
            };
        };
    };
    updateClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateClientRequest"];
        responses: {
            /** @description Updated client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
        };
    };
    deleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DeleteClientRequest"];
        responses: {
            /** @description Deletion result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    restoreClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RestoreClientRequest"];
        responses: {
            /** @description Restore result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
}
