openapi: 3.0.0
info:
  title: Golden Lotus Hotel API
  version: 1.0.0

paths:
  # Auth
  /api/auth/fetch:
    $ref: "./openapi/auth.yaml#/paths/fetch"

  /api/auth/login:
    $ref: "./openapi/auth.yaml#/paths/login"

  /api/auth/logout:
    $ref: "./openapi/auth.yaml#/paths/logout"

  # Employees
  /api/employees/create:
    $ref: "./openapi/employees.yaml#/paths/create"

  /api/employees/update:
    $ref: "./openapi/employees.yaml#/paths/update"

  /api/employees/delete:
    $ref: "./openapi/employees.yaml#/paths/delete"

  /api/employees/restore:
    $ref: "./openapi/employees.yaml#/paths/restore"

  /api/employees/get:
    $ref: "./openapi/employees.yaml#/paths/get"

  /api/employees/list:
    $ref: "./openapi/employees.yaml#/paths/list"

  # Clients
  /api/clients/create:
    $ref: "./openapi/clients.yaml#/paths/create"

  /api/clients/update:
    $ref: "./openapi/clients.yaml#/paths/update"

  /api/clients/delete:
    $ref: "./openapi/clients.yaml#/paths/delete"

  /api/clients/restore:
    $ref: "./openapi/clients.yaml#/paths/restore"

  /api/clients/get:
    $ref: "./openapi/clients.yaml#/paths/get"

  /api/clients/list:
    $ref: "./openapi/clients.yaml#/paths/list"

  # Room Types
  /api/room-types/create:
    $ref: "./openapi/room-types.yaml#/paths/create"

  /api/room-types/update:
    $ref: "./openapi/room-types.yaml#/paths/update"

  /api/room-types/delete:
    $ref: "./openapi/room-types.yaml#/paths/delete"

  /api/room-types/restore:
    $ref: "./openapi/room-types.yaml#/paths/restore"

  /api/room-types/get:
    $ref: "./openapi/room-types.yaml#/paths/get"

  /api/room-types/list:
    $ref: "./openapi/room-types.yaml#/paths/list"

  # Rooms
  /api/rooms/create:
    $ref: "./openapi/rooms.yaml#/paths/create"

  /api/rooms/update:
    $ref: "./openapi/rooms.yaml#/paths/update"

  /api/rooms/delete:
    $ref: "./openapi/rooms.yaml#/paths/delete"

  /api/rooms/restore:
    $ref: "./openapi/rooms.yaml#/paths/restore"

  /api/rooms/get:
    $ref: "./openapi/rooms.yaml#/paths/get"

  /api/rooms/list:
    $ref: "./openapi/rooms.yaml#/paths/list"

  # Reservations
  /api/reservations/create:
    $ref: "./openapi/reservations.yaml#/paths/create"

  /api/reservations/update:
    $ref: "./openapi/reservations.yaml#/paths/update"

  /api/reservations/delete:
    $ref: "./openapi/reservations.yaml#/paths/delete"

  /api/reservations/restore:
    $ref: "./openapi/reservations.yaml#/paths/restore"

  /api/reservations/get:
    $ref: "./openapi/reservations.yaml#/paths/get"

  /api/reservations/list:
    $ref: "./openapi/reservations.yaml#/paths/list"

components:
  schemas:
    Status:
      $ref: "./openapi/common.yaml#/components/schemas/Status"
    BaseResponse:
      $ref: "./openapi/common.yaml#/components/schemas/BaseResponse"
    ResultResponse:
      $ref: "./openapi/common.yaml#/components/schemas/ResultResponse"
